"""
Alembic migration script template.

This is a placeholder that will be used by Alembic when generating new migrations.
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers, used by Alembic
revision = '97538ee3703a'
down_revision = 'b80c191635d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('assigned_to', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priorityenum'), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.Enum('TO_DO', 'IN_PROGRESS', 'REVIEW', 'BLOCKED', 'DONE', name='statusenum'), nullable=True))

    op.execute("UPDATE tasks SET priority = 'MEDIUM' WHERE priority IS NULL")
    op.execute("UPDATE tasks SET status = 'TO_DO' WHERE status IS NULL")

    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priorityenum'),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('TO_DO', 'IN_PROGRESS', 'REVIEW', 'BLOCKED', 'DONE', name='statusenum'),
               nullable=False)
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tasks', sa.Column('section_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_index('ix_tasks_user_id_created_at', table_name='tasks')
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_section_id'), 'tasks', ['section_id'], unique=False)
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])

    op.create_foreign_key(None, 'tasks', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_workspace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_section_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.create_index('ix_tasks_user_id_created_at', 'tasks', ['user_id', 'created_at'], unique=False)
    op.drop_column('tasks', 'project_id')
    op.drop_column('tasks', 'section_id')
    op.drop_column('tasks', 'recurrence_rule')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'assigned_to')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'workspace_id')
    # ### end Alembic commands ###
